// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VehiclesApi.Data;

#nullable disable

namespace VehiclesApi.Migrations;

[DbContext(typeof(ApiDbContext))]
partial class ApiDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        #pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "7.0.0-rc.1.22426.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("VehiclesApi.Models.Vehicle", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Displacement")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Height")
                    .HasColumnType("float");

                b.Property<string>("ImageUrl")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Length")
                    .HasColumnType("float");

                b.Property<string>("MaxSpeed")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<double>("Price")
                    .HasColumnType("float");

                b.Property<double>("Width")
                    .HasColumnType("float");

                b.HasKey("Id");

                b.ToTable("Vehicles");
            });
        #pragma warning restore 612, 618
    }
}
